/**:
  ros__parameters:
    uav_parameters:
      mass: 1.8                  # Kg
      arm_length: 0.1854            # m
      num_of_arms: 4
      inertia:                     # Kg.m^2
        x: 0.07
        y: 0.07
        z: 0.07
      moment_constant: 0.0026     # m
      thrust_constant: 4.23e-06   # N.s^2/rad^2
      max_rotor_speed: 1000         # rad/s
      gravity: 9.81                # m/s^2
      input_scaling: 5
